FROM python:3.10-bookworm

# Create application directory
WORKDIR /app

RUN pip install uv==0.7.19

ADD pyproject.toml uv.lock ./

RUN mkdir /root/.ssh && touch /root/.ssh/known_hosts && \
  ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN --mount=type=secret,id=gitconfig,target=/root/.gitconfig \
  --mount=type=ssh \
  uv sync --no-dev --no-root --remove-untracked

# Install and run the program
ENTRYPOINT python3 -m python-template
