FROM python:3.13-bookworm

# Create application directory
WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:0.7.19 /uv /uvx /bin/

ADD pyproject.toml uv.lock .

RUN mkdir /root/.ssh && touch /root/.ssh/known_hosts && \
  ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN --mount=type=secret,id=gitconfig,target=/root/.gitconfig \
  --mount=type=ssh \
  uv sync --no-dev --no-install-workspace

# Install and run the program
ENTRYPOINT python3 -m python-template
