keywords_type = dict[str, dict[str, dict[str, dict[str, list[str]]]]]
test_keywords_en: keywords_type = {
    "fullfact": {
        "asylum": [
            "Small boat crossings",
            "Small boats",
            "Rwanda policy",
            "Visa applications",
            "Net migration",
            "Illegal migrants",
            "Asylum seekers",
            "Forced returns",
            "asylum hotels",
            "red days",
        ],
        "crime": [
            "Police officers",
            "Knife crime",
        ],
        "culture-wars": [
            "ULEZ",
            "Gender ideology",
            "Gender-neutral",
            "Conversion therapy",
        ],
        "defence": [
            "Napoleonic wars",
            "Defence spending",
            "Armed forces",
            "2.5% of GDP",
            "strategic defence review",
            "path to spending 2.5% of GDP on defence",
        ],
        "economy": [
            "Gross domestic product",
            "GDP",
            "Triple lock",
            "Disposable income",
            "Working people",
            "National Insurance",
            "National Insurance Contributions",
            "Debt burden",
            "Income tax",
            "National Debt",
            "Tax burden",
            "Council tax",
            "Tax bills",
            "GDP growth",
            "Tax cuts",
            "Tax rises",
            "22 billion shortfall",
            "22 billion black hole",
            "Employer contributions",
            "The Budget",
            "Inheritance tax ",
            "spending review",
        ],
        "education": [
            "Ghost children",
            "Private school",
            "VAT private school",
            "private schools bill ",
        ],
        "energy": [
            "Energy bills",
            "Nuclear plants",
            "Green levies",
            "Gas licences",
            "Wind farms",
            "Net zero",
            "Great British Energy",
            "Energy price cap",
            "Windfall tax",
            "fuel poverty",
            "carbon capture",
        ],
        "general": [
            "Record high",
            "record numbers",
            "Since WWII",
            "Since World War",
            "Since 2019",
            "Under the Conservatives",
            "since Labour",
        ],
        "health": [
            "NHS Strikes",
            "Waiting lists",
            "New hospitals",
            "Covid-19 Pandemic",
            "18-week",
        ],
        "housing": [
            "Social housing",
            "Affordable housing",
            "Council housing",
            "homelessness",
            "renters rights bill",
            "planning and infrastructure bill ",
            "150 major infrastructure projects",
        ],
        "poverty": ["Child poverty", "Food parcels", "Food banks", "benefit cuts "],
        "transport": [
            "HS2",
            "Great British Railways",
            "Train drivers",
            "potholes",
            "renationalisation ",
        ],
        "topical": [
            "Kemi Badenoch",
            "Donald Trump",
            "assisted dying bill",
            "football governance bill ",
            "Plan for Change",
            "grooming gangs",
            "council elections",
            " two-tier councils",
            "Ukraine aid",
            "Early release",
            "Prison overcrowding",
            "spending review",
            "steel tarrifs ",
            "nhs cuts",
            "civil service cuts",
        ],
    },
}


energy_pylons_text = [
    "The cost of reducing energy bills for people who live near pylons will be paid for by increasing average annual bills across the country by 80p, Energy Secretary Ed Miliband has told the BBC.",
    "Under the government's plans, households in Great Britain within 500m of new or upgraded pylons will get discounts of up to £2,500 over 10 years, equivalent to £250 a year.",
    "Miliband said the costs of the scheme were 'more than offset' by the benefits of the new infrastructure.",
    "He added that the idea was not about buying people off but 'recognising the service' they were doing for the whole country.",
    "However, rural campaign groups said it was 'impossible to put a price on the loss of a landscape'.",
    "A government-commissioned report found hundreds of miles of new pylons will be needed to meet its clean energy targets.",
    "But new infrastructure proposals have sparked fierce opposition from residents in parts of the country like Norfolk and Suffolk, with campaigners arguing they will destroy the countryside.",
    "The bill discounts, which will be funded by electricity suppliers, are expected to be in place from 2026.",
    "Suppliers are expected to recoup costs by passing them on to other customers.",
    "Miliband told the BBC: 'At the moment, we're having to switch off offshore wind farms because we haven't got the transmission infrastructure.",
    "'So everybody benefits from this.",
    "Everybody gets lower bills, and those who live near pylons are given a recognition of what they're doing.'",
    "The idea forms part of the government's Planning and Infrastructure Bill, which is due to be published this week.",
    "The legislation aims to speed up the building of new homes and infrastructure by cutting red tape and simplifying the planning process.",
    "The government has put the changes at the heart of its push for economic growth.",
    "Speaking to the BBC, Deputy Prime Minister Angela Rayner said local people would still be 'part of the process', but it would be 'streamlined' so development was not 'continually blocked for years and years'.",
    "Alongside money off bills, the government will publish new guidance on how developers should provide benefits to communities hosting transmission infrastructure, by funding projects like sports clubs, educational programmes or leisure facilities.",
    "The government said this would mean communities could get £200,000 worth of funding per km of overhead electricity cable in their area, and £530,000 per substation.",
    "Initial analysis estimates both bill discounts and community funds could see a total additional cost of between £1-2 a year for the average customer over 10 years.",
    "The government is also looking at how communities near onshore wind farms and other energy infrastructure can receive benefits.",
    "The plans were welcomed by RenewableUK, which represents the sector.",
    "The group's head of policy, James Robottom, said bill discounts would 'help to enable the roll-out of much-needed new grid infrastructure at a faster pace, so that we can make the most of the vast amounts of clean power we're producing'.",
    "However, Jackie Copley, campaign lead at CPRE, the countryside charity, said: 'Investing in local green spaces or improving community infrastructure would be a better way to spend this money.",
    "'Paying individuals comes with many problems, including questions of fairness, likely legal challenges, and the fact that it's impossible to put a price on the loss of a landscape.'",
    "The idea of giving people living near new pylons money off their energy bills was also proposed under the previous Conservative government.",
    "A government survey in 2024, external suggested 78% of people would find an energy infrastructure project more acceptable if they were offered discounts on their bills.",
    "Some energy companies already offer bill discounts to customers who live near infrastructure like wind turbines, while grants are also available for local communities affected.",
    "The bill also includes measures that would allow 'ready-to-go' energy projects to jump to the front of the queue for grid connections, replacing the current 'first come, first served' process.",
    "The government says the existing system is being 'clogged up' by speculative projects creating 10 year waits for 'viable infrastructure'.",
    "Meanwhile, the government has announced the number of bodies which get a say in planning decisions could be cut.",
    "Officials will consult on removing Sport England, the Theatres Trust and the Garden History Society from the list of 'statutory consultees', who are legally required to provide advice on decisions.",
    "The government said in some cases organisations were slowing down building, giving the example of a housing development in Bradford which was delayed because the application was thought to have not adequately considered the speed of cricket balls from a nearby club.",
]
energy_carbon_text = [
    "The government is committing billions of pounds to an 'unproven' green technology for reducing planet-warming gases without considering the impact on consumers' bills, MPs have warned.",
    "Carbon Capture, Utilisation and Storage (CCUS) facilities prevent carbon dioxide, produced by industry, being released into the atmosphere by capturing and storing it underground.",
    "In October, the government pledged nearly £22bn for CCUS facilities and three quarters of the money will be raised from consumer bills.",
    "But on Friday, the House of Commons' Public Accounts Committee raised serious concerns that the government had not properly assessed the financial impact on households and businesses.",
    "'It is an unproven technology, certainly in this country.",
    "And we are concerned this policy is going to have a very significant effect on consumers' and industry's electricity bills,' said Sir Geoffrey Clifton-Brown, chair of the Public Accounts Committee, a cross-party group of MPs which scrutinises public spending.",
    "Speaking to the BBC Today programme on Friday, Ed Miliband, Secretary of State for Energy, acknowledged the technology was novel but said it was vital for tackling climate change.",
    "”CCS is an innovative technology in terms of being used at scale, but all the expert advice - UK Climate Change Committee and others - say if we don't do this we are never going to cut global emissions,” he said.",
    "He added he was “100% committed” to the government's climate goals.",
    "The UK has a target to reach 'net zero' - meaning no longer adding to the total amount of greenhouse gases in the atmosphere, by 2050.",
    "As the country switches to renewable energy and away from fossil fuels for heating homes and running cars, greenhouse gas emissions like carbon dioxide, also known as CO2, will fall.",
    "But a small amount of gas will still need to be used to maintain electricity supply and there are some industries such as cement where there are few green alternatives.",
    "Carbon capture could prevent the CO2 produced by these processes from entering the atmosphere - and the government has bet achieving its climate goals on it.",
    "Both the UK's independent climate watchdog and the UN's climate science body, the IPCC, agree that CCUS will be needed if countries want to reach net zero and avoid the worst impacts of climate change.",
    "By 2050, the government wants carbon capture and storage to prevent the emitting of 50 million tonnes of CO2 - more than 10% of what the country currently releases - and has committed £21.7bn to achieving this goal.",
    "The funding, announced in October, will go towards clusters of carbon capture projects in Merseyside and Teesside, which it said would create thousands of jobs and attract private investment.",
    "Dr Stuart Jenkins, research fellow at the University of Oxford, pushed back on the committee's assessment of the technology.",
    "'I really don't like the phrase 'unproven' technology, it is not representative of the status of the technology as an engineering problem,' he said.",
    "Although there are no commercial CCUS sites in the UK, there are 45 commercial facilities already operating globally capturing around 50 million tonnes of CO2, and there are more than 700 being proposed or developed, according to the International Energy Agency, external.",
    "But Dr Jenkins did agree with the Public Accounts Committee that there were questions about whether the government's current funding model was sustainable.",
    "The committee have recommended that the full financial impact of the programme on consumers be properly assessed, taking account of cost-of-living pressures.",
    "The committee did recognise the importance of early government support for novel technologies like CCUS to give confidence to the industry.",
    "But it added it 'was surprised' to discover that the government had signed two contracts with CCUS developers last year and not guaranteed that if the projects were successful that the government - and the public - would receive profits or benefits such as lower energy bills.",
    "'If you were a venture capitalist investing this sort of sum of money, which is effectively what the taxpayers are doing here, you would expect to have a big equity stake in this whole thing,' said Sir Clifton-Brown.",
    "His committee recommended that any future contracts be changed to include profit-sharing mechanisms.",
    "The government said that it expected the £21.7bn funding for CCUS to unlock £8bn in private sector investment over the next 25 years.",
    "Mirte Boot, co-founder of Carbon Balance Initiative and research associate at University of Oxford, said her team's research suggests a better long-term model for financing could be introducing a carbon storage mandate - placing a legal obligation on fossil fuel producers to store a share of the CO2 they produce, or face a financial penalty.",
    "'We argue that carbon storage mandates on fossil fuel producers are fair whilst also providing the kind of investment certainty that companies need,' she said.",
]
energy_wind_text = [
    "Wind provided more electricity than ever last year as the UK moved further away from planet-warming fossil fuels to power the nation, new data shows.",
    "Wind generated nearly 83 terawatt-hours (TWh) of electricity across Great Britain (England, Wales and Scotland), up from nearly 79TWh in 2023, show figures from the National Energy System Operator (Neso), which coordinates electricity distribution.",
    "Electricity generation from major fossil fuel power stations fell to just over a quarter of the total last year as other renewable sources, such as solar, also rose, along with electricity imports.",
    "The government wants less than 5% of electricity to come from polluting fossil fuels by 2030.",
    "Neso - the government's independent system planner and operator for the energy transition - has previously described the government's 'Clean Power 2030 Action Plan' as 'achievable' but 'at the limit of what is feasible'.",
    "The government considers clean electricity to include renewables, such as wind, solar, hydropower and bioenergy, as well as nuclear power.",
    "Together, these sources generated around 56% of Great Britain's electricity in 2024 - a new high, according to preliminary Neso data that will be confirmed this week.",
    "Major fossil fuel generation (mainly gas) fell to 26%, while a further 16% came from imported electricity.",
    "Neso data does not cover Northern Ireland, which has its own electricity transmission system operator, SONI.",
    "The figures only include fossil fuel and biomass generation from major power stations connected to the main transmission network.",
    "For these sources, Neso does not include smaller-scale operators that feed in electricity at a local level, although typically these contribute a relatively small fraction of fossil fuel power.",
    "As a result, government figures for 2024 due in March, which will take into account all power sources, may differ slightly from Neso's data.",
    "But the direction of travel is clear.",
    "Back in 2014, wind and solar accounted for around 10% of Great Britain's electricity.",
    "That has now risen to about a third, according to Neso's figures.",
    "Over the same period, fossil fuel generation has fallen by more than half.",
    "That is mainly thanks to a sharp fall in coal generation - the dirtiest fossil fuel - with the UK's final coal power station closing in 2024.",
    "Gas generation has also begun to decline.",
    "This has helped to significantly clean up Britain's power generation.",
    "In 2024, each kilowatt-hour (kWh) of electricity generated 124g of planet-warming carbon dioxide on average - a new low, and down from 419g/kWh in 2014, according to Neso.",
    "But gas remains a crucial part of the UK's electricity mix, helping to maintain power supply when output from weather-dependent wind and solar sources drops.",
    "Britain's wind turbines can generate huge amounts of electricity when weather conditions are right, as shown by the darkest blue in the chart below.",
    "On around 10 days in December alone, more than 50% of Great Britain's electricity generation came from wind.",
    "However, there are of course less windy periods when electricity generation from wind drops.",
    "In the longer term, these gaps could be filled using emerging green technologies, such as batteries, to store energy during windier times.",
    "There could also be extra incentives for people to use electricity during windy periods, for example by offering cheaper prices.",
    "But for now, gas power stations, a ready source of on-demand energy, need to be fired up to fill the gaps.",
    "For three consecutive days between 11-13 December, for example, more than 60% of electricity generation came from gas as wind output dropped.",
    "In its plan for meeting the 2030 clean energy target published last month, the government committed to keeping a reserve capacity of gas power stations for this purpose.",
    "Last month Claire Coutinho, Conservative shadow secretary of state for energy security, said Labour's 'rush' to decarbonise the electricity system by 2030 would push up electricity prices and cause more hardship for people across Britain.",
    "'We need cheap, reliable energy - not even higher bills,' she said.",
]
education_private_schools_text = [
    "A group representing 1,400 private schools will press ahead with plans for a legal challenge against the government's introduction of VAT from January, the BBC can reveal.",
    "In a board meeting on Thursday, the Independent Schools Council (ISC), the body which includes most independent schools in the UK, voted to pave the way for legal action.",
    "Lord David Pannick KC, one of the country's leading barristers in cases relating to government decisions, is to lead the challenge which will be brought on behalf of parents, including those with children with special educational needs and disabilities (Send).",
    "A Treasury spokesperson told the BBC they do not comment on potential litigation matters.",
    "Chancellor Rachel Reeves confirmed private schools would no longer be exempt from VAT in the autumn Budget, saying the money raised would help “provide the highest quality of support and teaching” in the state sector.",
    "The government has estimated it would raise £460m extra to spend on state schools next year, rising to £1.7bn by 2029/30.",
    "The ISC is hoping for a judicial review of the government's policy, which will focus around claims of breaches of the European Convention on Human Rights.",
    "The action will be brought around Article 14, the prohibition of discrimination, and Article 2 of the First Protocol, the right to education.",
    "The ISC informed its members of its plans to take forward legal action, in an email to private schools on Thursday afternoon.",
    "The group says its legal claimants will be parents who argue they cannot find an alternative education for their children in the state sector, and are likely to include families with children with special educational needs.",
    "Chief Executive Julie Robinson says they “will be defending the rights of families who have chosen independent education, but who may no longer be able to do so as a direct result of VAT on their fees”.",
    "“We continue to ask the government to work with us to mitigate the risks of this policy on specialist arts education, on low-fee faith schools, on small girls' schools and on children with Send.”",
    "Rebecca Frost, a nurse and mother of three children in private school in Somerset, is pleased the action is being taken.",
    "All of her children have special educational needs.",
    "She is currently applying for an education, health and care plan (EHCP), as she will have to pay an additional £9,000 a year once the changes come into place.",
    "“State education was unable to meet their needs despite trying various different options,” Mrs Frost says.",
    "“I could not put them back there”.",
    "In an impact assessment released on Wednesday, the government confirmed that only those children with a local authority EHCP, with a private school named on it, will be exempt from the VAT policy.",
    "It added that 'carving all children with Send out of this policy would carry a significant cost, and therefore undermine the government's ability to improve education for the 94% of school children in the UK that attend state schools'.",
    "It promised to increase a grant to help cover boarding school fees for children of military families to take account of rising fees.",
    "But its assessment also concluded that small faith schools will not be exempt as they “are likely to be less than proportionately impacted if their income is derived not only from fees but also from other sources, such as voluntary donations from the community, or support from religious organisations”.",
    "Aliya Azam is from the Al Khoei Foundation, which represents two Muslim faith schools in London - they charge fees from £1,250 to £6,990.",
    "She says parents are being forced to choose “between their faith and financial survival”.",
    "“We support the legal challenge because faith-based education deserves protection, not a price tag”, she added.",
    "The plans will lead to fees rising by an average of 10%, and will see about 35,000 students moving to state schools over the longer term - around 6% of the current private school population, according to the government.",
    "The money raised is expected to help fund 6,500 new teachers in England.",
]
transport_rail_renationalisation = [
    "The renationalising of train companies will not necessarily bring cheaper rail fares but should reduce cancellations and late trains, the UK transport secretary has suggested.",
    "South Western Railway is to become the first train operator nationalised under the Labour government, ministers announced on Wednesday.",
    "Greater Anglia and C2C will also be brought into public ownership next year.",
    "Heidi Alexander, who took over at the transport department less than a week ago after the resignation of Louise Haigh, said the “primary aim” of the move was “to improve reliability and clamp down on the delays, the cancellation, the waste and the inefficiency that we've seen over the last 30 years”.",
    "“We've had private train-operating companies running train services in this country over the last few decades, and it clearly hasn't worked,” she told the BBC.",
    "She said bringing the operators into public ownership was a “first step” to a “more integrated and unified railway”, and pointed to the impact of bringing LNER and Southeastern into public ownership.",
    "“So if you look at LNER for example, we have reduced the number of trains that are cancelled because of staff shortages to basically zero, and we reduced other cancellations to about 5%.",
    "“Southeastern, which is also now in public ownership, is in the top five of train operators for punctuality.”",
    "Alexander declined to say what the cost of nationalising rail operators would be, but claimed it would be “a fraction” of what was paid in management fees to train companies.",
    "She told LBC radio: “So it will be a fraction of the costs, for example – to bring them over and also … set up Great British Railways – a fraction of what we're paying in terms of the management fees.”",
    "“At the moment, we pay roughly about £150m in management fees to the train operating companies.”",
    "The government has chosen which rail operators to renationalise first based on when their contracts expire in order to avoid paying compensation to train companies, she said.",
    "“We will take the train operating companies back into public ownership when their current contracts expire,” she said.",
    "“And so the expiry date for South Western is in May of next year, and the expiry date for C2C is July.",
    "“There is also a provision within the current contracts to issue an expiry notice when the train operator has completed a sort of minimum term of its contract.”",
    "“We have reached that point with Greater Anglia, and so we will be issuing an expiry notice for Greater Anglia in due course, giving them notice about the exact date on which that transfer will happen.”",
    "“We decided to proceed in that way because that means we don't have to pay compensation to the train operating company.”",
    "Alexander said she needed to have a “mature” relationship with trade unions to provide an efficient rail service, telling Times Radio: “There is a fundamental need for a reset of the relationship because the previous government pursued a scorched earth policy when it came to the rail unions.",
    "“They saw the trade unions as a problem purely to be managed as opposed to partners to work with.”",
    "“Now, there will be some occasions on which the trade unions are right about things, there will be some occasions on which the trade unions are wrong.”",
    "When Alexander ran Transport for London as a deputy mayor under Sadiq Khan, “there were a number of occasions on which strikes happened on the network, and we resolved those strikes by negotiating with the trade union”, she said.",
    "She added: “We're going to have to work together to get to a really efficient railway that provides good value for money for both the fare payers and the taxpayers.”",
    "“And we're only going to do that if the transport secretary has a mature relationship with the trade unions.”",
]
transport_ulez = [
    "Pollution in London has reduced after the controversial expansion of the Ultra Low Emission Zone (Ulez), according to City Hall.",
    "Levels of nitrogen dioxide (NO2) - a toxic gas that exacerbates asthma, impedes lung development, and raises the risk of lung cancer - across all of London is estimated to have decreased by 27%, the report found.",
    "The zone, which aims to cut pollution by charging drivers of vehicles which do not meet emission standards, was expanded by London's mayor Sir Sadiq Khan to outer London in August 2023.",
    "The Labour mayor praised the results while the Conservatives on the London Assembly said the data relied on 'maybes, possibilities, assumptions, and straight up fantasy'.",
    "When the scheme was expanded, it sparked protests as opponents said the scheme was rushed and the benefits were not worth the financial cost for those who had to change their vehicles.",
    "Opponents also said the changes would have happened anyway as drivers took notice of the existing Inner London Ulez zone.",
    "According to the study, which looked at data for 12 months from September 2023, air quality has improved at 99% of air quality monitoring sites across London since 2019, and London's air quality is improving at a faster rate than the rest of England.",
    "It also found:",
    "NO2 levels in outer London were 4.8% lower than expected had the expansion not gone ahead",
    "Particulate matter 2.5 (PM2.5) exhaust emissions from cars and vans in outer London were estimated to be 31% lower",
    "The London-wide compliance rate for vehicles subject to Ulez standards after the first year of the expansion (as of September 2024) was 96.7%",
    "For people living near London's busiest roads, there was an estimated 80% reduction in 2023 in people exposed to illegal levels of pollution, increasing to 82% in outer London, compared without Ulez",
    "There were nearly 100,000 fewer non-compliant vehicles detected in London on an average day in September 2024 compared with June 2023.",
    "The results have been checked by a group of independent air quality analysis experts.",
    "London boroughs which opposed Sir Sadiq Khan's expansion of the zone saw the largest reductions in nitrogen oxides (NOx) in 2024.",
    "The report found the level of decreases were 15.4% in Sutton, 15.3% in Croydon, and 15.2% in both Bromley and Harrow.",
    "All opposed the expansion of ULEZ.",
    "Reacting to the report, Sir Sadiq said: 'With boroughs in outer London seeing some of the biggest reductions in harmful emissions and London's deprived communities also seeing greater benefits, this report shows why expanding Ulez London-wide was so important.'",
    "'Indeed, the air in outer London is now as good as the air in the rest of England,' he said.",
    "'When I first became mayor, King's College said it would take 193 years to bring our air within lawful limits.",
    "'We have done it this year, 185 years early.",
    "'Thanks to Ulez and our other policies, all Londoners are now breathing substantially cleaner air - but there is still more to do.'",
    "But Keith Prince, Assembly member and transport spokesman for the Conservatives said: 'The mayor is supposedly comparing these results to a London where the Ulez scheme didn't happen, as though we can accurately measure such a thing.",
    "'How he can say that Ulez is responsible for London's air clearing up with a straight face is beyond me - the data relies on maybes, possibilities, assumptions, and straight up fantasy in order to justify a project that is saddling TfL (Transport for London) and Londoners with mountains of debt.'",
    "In September 2023, the mayor said Ulez expansion would help tackle climate change.",
    "But the City Hall report found that when looking at London as a whole, carbon dioxide (CO2) emissions from cars and vans were only 1% lower than they would have been without the London-wide Ulez expansion.",
    "That equates to a CO2 emission saving of 35,000 tonnes across London in 2024.",
    "Since 2019, CO2 emissions are estimated to be 813,000 tonnes lower across London, equivalent to a 2% reduction.",
    "The issue of Ulez expansion was a key issue during the 2024 mayoral election with the Conservative candidate Susan Hall saying she would scrap it.",
    "In the Uxbridge by-election in 2023, the then Labour candidate (and now Uxbridge MP) Danny Beales blamed the expansion for his loss to the Conservative candidate who said they would oppose it.",
    "Four London authorities, Bexley, Bromley, Harrow, Hillingdon, and Surrey County Council also took a legal challenge to the High Court in July but lost.",
    "Reacting to the latest report, Colin Smith, leader of Bromley Council, criticised the 'one size fits all lunacy' of Ulez expansion.",
    "He said it had 'destroyed care networks', forced people to change jobs, and created a 'huge financial expense for people and businesses having to buy new vehicles they didn't want or need'.",
    "Simon Birkett, founder and director of Clean Air in London said the report showed the scheme had worked and that in combination with 'cleaner' buses and taxis, Ulez had helped London slash NO2 concentrations by two thirds near busy roads and had edged the city closer towards World Health Organisation guidelines.",
    "Rosamund Adoo-Kissi-Debrah whose daughter Ella died after air pollution made a material contribution to her death, said she was delighted.",
    "'My daughter Ella died from emissions from the South Circular Road close to where we live, and I will not stop until everyone in London can breathe safe, clean air, regardless of where they live in the city.'",
    "Professor Tony Travers from the London School of Economics said Ulez had become a way of attacking the mayor, especially in the run-up to last year's mayoral election.",
    "'Opposition (to Ulez) was greater in some parts of the media than across the population more generally.'",
    "'With the election long over and the policy implemented, his opponents have moved on,' he said.",
    "'Crime (or perceptions of it) is more likely to be used by his opponents now as their issue of choice.",
]
transport_tube_ebikes = [
    "Non-folding e-bikes will be banned from 31 March on most of the Transport for London (TfL) network, it has announced.",
    "The operator said customers travelling with these kinds of e-bikes - including ones converted to e-bikes using kits - will not be permitted to travel on most services such as the Tube, Overground, Elizabeth line and DLR.",
    "It comes after the Aslef union said earlier this month it was considering balloting members for strike action over e-bikes being allowed on the London Underground.",
    "TfL said it had made the decision to 'ensure the safety of customers and staff' and added it had carried out a review of safety of e-bikes on the network.",
    "TfL drew on its own analysis which it said suggested bikes adapted using electronic conversion kits posed a greater fire risk than purpose-built e-bikes, although it pointed it could be hard to differentiate between modified and unmodified e-bikes.",
    "It said it was instigating the ban 'until improved product safety measures are in place for converted cycles, batteries and chargers'.",
    "It comes after a small number of e-bike fires on the transport network, including one which exploded and caught fire on a Tube station platform in north-west London in February.",
    "Last March an e-bike also exploded and burst into flames on a platform at Sutton railway station.",
    "The operator said it 'will keep these changes under review, pending any future changes to legislation by the government regarding e-bike safety standards'.",
    "Existing rules around non-folding bikes and e-bikes will remain in place, including rules stipulating that no e-bikes are permitted on the IFS Cloud Cable Car and that no non-folding bikes are allowed on buses or trams.",
    "TfL stressed non-foldable e-bikes would continue to be permitted on the Silvertown Cycle Shuttle Service, Woolwich Ferry, river services depending on the operator and coach services depending on the operator.",
    "Dan Parsons, from London Bridge e-bike shop Fully Charged, said the problem is differentiating between the good and the bad.",
    "'By banning all, it muddies the waters, and the UK population doesn't necessarily know the difference between good and bad, and just assumes that all [e-bikes] are bad.",
    "'In an environment when we need to increase the amount of green transportation, we're throttling that.'",
    "Lilli Matson, TfL's chief safety, health and environment officer, said: 'We have been working closely with the London Fire Brigade (LFB) on a review of the safety risks associated with e-bikes on our network.",
    "'This safety ban will play a vital role in keeping our transport system safe for everyone, and we continue to work with partners in government and beyond to improve e-bike safety.'",
    "Charlie Pugsley, LFB's deputy commissioner for prevention, protection and policy, said the brigade 'welcomes this move... as it acknowledges the risks that we know e-bike batteries can pose'.",
    "'While we recognise the sustainable benefits e-bikes, and micromobility generally, bring to our city, the reality is that across London we have been seeing an e-bike or e-scooter fire every other day, on average, and we have particular concern about the risk posed by conversion kits or modified e-bikes,' he explained.",
    "Mayor of London Sir Sadiq Khan said: 'The safety of Londoners is my top priority and, while most e-bikes are safe, there have been a small number of incidents where non-foldable e-bikes have caught fire on the transport system, which have caused me great concern.",
    "'I have asked TfL to continue to work with government and partners to improve e-bike safety as we build a safer London for everyone.'",
]
crime_london_knives = [
    "London is under siege.",
    "Criminals rule the streets like they never have before, and the police are not taken seriously.",
    "Sadiq Khan, who is in charge of the police in London, has arrogantly ignored this problem for eight long years.",
    "He doesn't think he needs to listen to the victims of crime.",
    "He doesn't think he needs to listen to anyone but himself.",
    "And he would rather go on holidays, set up beach parties and sell his terrible book.",
    "Our streets have become battlegrounds.",
    "Parents worry for the safety of their children, with the news bleak each week - children are frightened of being stabbed on their way to school, or even in the classroom.",
    "And when the police don't turn up if a crime is considered too 'minor' by Sadiq Khan, it should be no surprise that Londoners' faith in our Metropolitan Police is in the gutter.",
    "It is upsetting to think about the human cost of Sadiq Khan's failures on crime.",
    "But we must if we want to do something about it.",
    "As of last month, over 1,000 people have been killed since Sadiq Khan was elected.",
    "That's 1,000 families grieving.",
    "1,000 families who will never forget their losses.",
    "And then there's the survivors of violence, who must live with trauma.",
    "Imagine feeling scared every time you walk out your front door in case someone attacks you.",
    "And the fear sadly isn't unreasonable.",
    "There is more than double the chance you will be threatened with a knife in London today, than you were when Sadiq Khan was elected all those years ago in 2016.",
    "Women are forced to take extra care to protect themselves, when drink spiking has quadrupled, and sexual offences have increased by nearly half under Sadiq Khan.",
    "It is a disgrace.",
    "And Londoners deserve better.",
    "But there is a silver lining.",
    "I've been listening to Londoners, sharing the fears and worries you have about the direction of our great City.",
    "And this week, I stood up and said enough is enough.",
    "I've unveiled a plan, backed by the Home Secretary, that will deliver a safer London for you and your children.",
    "Under my plan, we will put police back in the communities they serve with a return to borough-based policing.",
    "We will make our schools knife-free zones.",
    "By giving schools knife arches, we will ensure our kids can focus on their classes instead of worrying about their safety.",
    "I will boost stop and search, giving frontline police officers knife detection wands—making it faster and less intrusive.",
    "That means when people are stopped by the police, frisking won't be the go-to.",
    "If you've been to a gig, through the airport, or perhaps to a club in London lately, you'll have seen those wands.",
    "Hand-held metal detectors are passed up and down the body and locate knives.",
    "All without having to be 'handled' by anyone.",
    "Just imagine how much that'll help defuse these often-tense situations; how much it will help rebuild the trust many people have lost in our coppers.",
    "Robberies, burglaries, and thefts will be taken seriously again.",
    "I will deploy specialised units to hunt down the perpetrators, sending a clear message: London's not your playground anymore.",
    "Sadiq Khan has had eight years to show us where his priorities lie.",
    "And time and again, he's shown that Londoners' safety doesn't matter to him.",
    "Crime rising? 'Not my fault,' he says.",
    "The Met in crisis? 'Nothing to do with me,' he suggests.",
    "Well, we say, 'No more.'",
    "As we look ahead to the election, the choice couldn't be clearer.",
    "Do we want another four years of Sadiq Khan's London, where crime spirals out of control and our pleas for help fall on deaf ears?",
    "Or do we choose a new direction—a safer, stronger London where our children don't dodge knives but chase dreams?'",
    "'This election isn't just about who gets to sit in the mayor's office.",
    "It's about taking a stand for the London we know and love.",
    "The choice is ours.",
    "Let's choose wisely.",
    "Let's choose safety.",
    "Let's make London a place where fear doesn't walk our streets.",
    "Together, we can turn the tide.",
]
health_assisted_dying = [
    "The government expressed concerns about the timeline for implementing assisted dying, the BBC understands, before measures were tabled to delay when it could be available.",
    "Kim Leadbeater, the Labour MP bringing the bill, said she was 'disappointed' to be proposing deferring when it must be in force until 2029.",
    "Some MPs expressed concern this means it might not be in place until after the next general election.",
    "Officials and civil servants have been advising Leadbeater on drafting amendments, including suggesting changes the government wants.",
    "A spokesman for Leadbeater said: 'Kim hopes and believes the service can be delivered more quickly if it becomes law later this year.'",
    "Part of the reason for postponing the deadline is to allow time to set up training and systems for what would be an entirely new service.",
    "Changes made to the bill since MPs voted in favour, including a new commission and panel system to oversee application, have added to that.",
    "Leadbeater's new amendment changes the maximum implementation period from two years to four years.",
    "However if all the systems are ready before four years, assisted dying will go ahead earlier than the deadline.",
    "It is understood there is disagreement among ministers about the delay to implementation, with some believing it is a mistake.",
    "The government is officially neutral on the bill with many ministers supporting it.",
    "'I cannot pretend that I'm not disappointed about extending the commencement period,' Leadbeater told MPs on the committee, which finished its scrutiny of the bill late last night.",
    "But she said the change created a 'four-year backstop', adding: 'It doesn't say it cannot be implemented before then.'",
    "Both MPs supportive of assisted dying and those opposed have expressed dismay.",
    "Tom Gordon, a Liberal Democrat MP in favour of the bill who sits on the committee, said other countries had implemented similar laws in much less time.",
    "'The current law is failing terminally ill people, forcing them to suffer unbearably, travel abroad to die or risk their families facing police investigations. This amendment would prolong that suffering unnecessarily,' he said.",
    "'Delaying implementation risks pushing it beyond the next election, where it could be abandoned altogether.'",
    "Jess Asato, a Labour MP who is against the bill, said: 'Putting an arbitrary timeline on such a complex issue was never a sensible way to make life or death legislation.",
    "'This last-minute switch demonstrates again just how chaotic this whole process has been with substantial last-minute changes to core sections of the bill.'",
    "The bill will now return to the whole House of Commons and, if MPs approve it, then it will go to the Lords for further debate and scrutiny.",
]

arabic_environment = [
    "سرايا - يكون الطقس اليوم الثلاثاء، لطيف الحرارة في اغلب المناطق، وحارا نسبيًا في الأغوار والبحر الميت والعقبة، مع ظهور الغيوم على ارتفاعات منخفضة، وتكون الرياح شمالية غربية معتدلة السرعة تنشط بين الحين والاخر مثيرة للغبار خاصة في مناطق البادية.",
    "وبحسب تقرير ادارة الارصاد الجوية، يطرأ يوم غدٍ الأربعاء، ارتفاع قليل على درجات الحرارة، ويكون الطقس لطيف الحرارة في اغلب المناطق، وحارا نسبيًا الى حار في الأغوار والبحر الميت والعقبة، مع ظهور بعض الغيوم على ارتفاعات منخفضة، وتكون الرياح شمالية غربية معتدلة السرعة تنشط على فترات مثيرة للغبار خاصة في مناطق البادية.",
    "اما الخميس والجمعة، يطرأ ارتفاع على درجات الحرارة، ويكون الطقس معتدل الحرارة في المناطق الجبلية والسهول وحارا في البادية و الأغوار والبحر الميت والعقبة، وتكون الرياح شمالية غربية معتدلة السرعة.",
    "وتتراوح درجات الحرارة العظمى والصغرى في شرق عمان اليوم ما بين 26 - 15، درجة مئوية، وفي غرب عمان 24 - 13، وفي المرتفعات الشمالية 21 - 9،وفي مرتفعات الشراة 22 - 11، وفي مناطق البادية 31 - 18، وفي مناطق السهول 25 - 15، وفي الأغوار الشمالية 33 - 17، وفي الأغوار الجنوبية 36 - 22، وفي البحر الميت 35 - 20، وفي خليج العقبة 36 - 21 درجة مئوية.",
]
arabic_education = [
    "في مقاله الأسبوعي بصحيفة نيويورك تايمز، قال الكاتب المعروف توماس فريدمان إن محللي مؤشرات الأسهم في بورصة وول ستريت في نيويورك بدؤوا بالاستهزاء من سلوك الرئيس الأميركي دونالد ترامب.",
    'وقالوا إن أفضل طريقة للتنبؤ بما سيقدم عليه، ومن ثم جني الأموال من تصرفاته، هي ممارسة "تجارة تاكو"، وهو مصطلح يعني أن "ترامب دائما ما يتراجع عن تهديداته"، خاصة عندما يتعلق الأمر بالتعريفات الجمركية "المتهورة".',
    "وأضاف أن هذه السخرية من التقلب في المواقف التي تثير جنون ترامب ليست دقيقة فحسب، بل تستحق أن تُستخدم على نطاق أوسع.",
    'وأورد الكاتب أمثلة للدلالة على تلك التقلبات، وقال إن ترامب تارة ما يُنحِّي أوكرانيا جانبا، وفي اليوم التالي يبتزها للحصول على معادنها النادرة، ثم ما تلبث أوكرانيا أن تعود بعدها إلى بيت الطاعة. وفي أحد الأيام يكون الرئيس الروسي فلاديمير بوتين صديقا له، وفي اليوم التالي يكون "مجنونا" برأيه.',
    'ويمضي فريدمان بسرد الأمثلة للتأكيد أن تصرفات الرئيس الأميركي "تثير السخرية"، فيقول إن ترامب يعلن في يوم من الأيام أن كندا ستصبح الولاية الأميركية رقم 51، وفي اليوم التالي يستهدفها بالرسوم الجمركية.',
    'وفي يوم يتفاخر بأنه لا يوظِّف سوى "أفضل" الأشخاص، وبعدها مباشرة يطرد أكثر من 100 خبير في مجلس الأمن القومي الأميركي بعد أسابيع فقط من تعيين العديد منهم.',
    'ويعتقد الكاتب أن الرئيس يمارس سلطته فقط بدافع من حدسه "غير المنضبط"، ومن دون دراسة وافية أو تنسيق كبير بين أجهزة الدولة، أو بمعزل عنها، زاعما أن ترامب "لا يحترم هياكل السلطة التنفيذية عند اتخاذ القرارات، ويجعل رفيقه في ممارسة لعبة الغولف (ستيفن ويتكوف) يتصرف كوزير للخارجية، في حين أن وزير الخارجية (الأصلي) ماركو روبيو يؤدي دور سفيره في بنما".',
    "ويسترسل في انتقاداته اللاذعة، وهو الكاتب المعروف بميوله الليبرالية، فيقول إن ترامب يطمس كل الخطوط الفاصلة بين واجباته القانونية ومصالحه الشخصية.",
    "وفي اعتقاد فريدمان أن ذلك يعني أن أميركا لم تعد تحكمها إدارة تقليدية، بل تديرها منظمة ترامب التي يملكها الرئيس نفسه.",
    "وعقد مقارنة بين ولايتي ترامب الرئاسيتين الأولى والثانية. وقال إن الرئيس أحاط نفسه في الولاية الأولى ببعض الأشخاص من ذوي الثقل الذين كانوا بمنزلة أحزمة أمان تقيه من السقوط في المشكلات، أما في الثانية فقد أحاط نفسه فقط بالمتملقين الذين يُضخِّمون أفعاله.",
    "وعزا السبب الذي يجعل ترامب يتصرف بهذا الشكل إلى أن الديمقراطيين اليوم في غاية الضعف، والجمهوريون جبناء أكثر من اللازم، وشركات المحاماة الكبرى مفلسة أخلاقيا، والمسؤولون في الحكومة عاجزون عن فعل أي شيء.",
    "وانتقد فريدمان قرارات ترامب بفرض الرسوم الجمركية، وقال إنها وجهت ضربة لصناعة السيارات الأميركية برمتها حتى إن شركات مثل فورد وجنرال موتورز وستيلانتس أعلنت أنها لا تستطيع تقديم توقعات لأرباحها لبقية عام 2025، مشيرة إلى الغموض الذي يكتنف تطبيق الرسوم الجمركية والاضطرابات المحتملة في سلاسل التوريد.",
    "وأكد أن رد فعل الصين كان متوقعا بعد أن فرض ترامب رسوما جمركية بنسبة 145% على جميع صادراتها إلى الولايات المتحدة، فكان أن أوقفت فجأة تصدير المعادن النادرة التي تدخل في صناعة السيارات والطائرات المسيرة والروبوتات والصواريخ التي تنتجها أميركا.",
    'وقال فريدمان إن "هوس" ترامب بتدمير صناعة السيارات الكهربائية الأميركية، التي كان الرئيس السابق جو بايدن يحاول بناءها، يقوض جهود الولايات المتحدة لمنافسة الصين في مجال البطاريات الكهربائية.',
    "ووفق تعبيره، فإن البطاريات هي النفط الجديد؛ فهي ستعمل على تشغيل النظام البيئي الصناعي الجديد للسيارات الذاتية القيادة والروبوتات والطائرات المسيرة والتكنولوجيا النظيفة، التي تعمل بالذكاء الاصطناعي.",
    "وفي هذا الصدد، يؤيد فريدمان ما ذهب إليه الكاتب الاقتصادي نواه سميث من أن تبعات ذلك ستكون إضعاف قدرة أميركا على إنتاج طائرات مسيرة رخيصة الثمن تعمل بالبطاريات، وهي التي استخدمتها أوكرانيا قبل أيام لتدمير جزء من الأسطول الجوي الروسي، والتي يمكن أن تستخدمها الصين بالطريقة نفسها ضد حاملات الطائرات الأميركية.",
    "وانتقل الكاتب بعد ذلك إلى الحديث عن إستراتيجية ترامب التعليمية، فقال إن واشنطن لا يمكنها أن تضع حاجزا تجاريا ذا مغزى أمام الصين ما لم تكن لديها أيضا خطة تعليمية تعزز الصناعة المتقدمة.",
    "وأشار في هذا الصدد إلى أن الجامعات الصينية تركز بشكل كبير على تدريس العلوم والتكنولوجيا والهندسة والرياضيات لدرجة أنها تُخرِّج كل عام حوالي 3.5 ملايين طالب في هذه التخصصات، وهو أقل بقليل من عدد خريجي برامج الزمالة والبكالوريوس والماجستير والدكتوراه في جميع المساقات في الولايات المتحدة.",
    "واختتم الكاتب مقاله بأن الولايات المتحدة، لكي تنافس في اقتصاد المستقبل الذي يعتمد على الذكاء الاصطناعي، عليها أن تسدّ النقص الحاد في أعداد المهندسين، مضيفا أنه لن يتأتى لها ذلك إلا بقبول عشرات الآلاف من طلاب الهندسة والمهندسين من الصين والهند على وجه الخصوص.",
]
arabic_science = [
    "يركز يوم البيئة العالمي 2025 الذي يصادف 5 يونيو/حزيران، على إنهاء التلوث البلاستيكي على مستوى العالم، حيث يُعدّ تلوث البلاستيك من أكثر القضايا البيئية إلحاحا في حياتنا. ومع استمرار تزايد إنتاج البلاستيك المستخدَم لمرة واحدة، تزداد صعوبة إدارته والتخلص من تأثيراته.",
    "تدخل سنويا ملايين الأطنان من النفايات البلاستيكية إلى البيئة، وتمتد آثارها عبر المحيطات والمجاري المائية واليابسة، وأصبحت أنهار العالم ومحيطاته وبحاره طرقا للنقل ومكباتٍ للبلاستيك الناتج عن الأنشطة البشرية.",
    "وكان يمكن لمعاهدة عالمية بشأن البلاستيك أن توفر إطارا دوليا منسقا لمعالجة إنتاج البلاستيك واستخدامه والتخلص منه بما يعزز الممارسات المستدامة ويقلل النفايات من مصدرها، لكن إقرار هذه المعاهدة يبدو أنها في مسار متعثر.",
    "ويرى أنصار البيئة أنه من خلال توحيد جهود الحكومات يمكن لهذه المعاهدة أن تحفز الابتكار في المواد البديلة، وتعزز جهود إعادة التدوير، وتضع التزامات قانونية صارمة للحد من التلوث البلاستيكي.",
    "تشير التقديرات إلى أن أكثر من 8 ملايين طن من النفايات البلاستيكية تنتهي في المحيطات سنويا. ولأن معظم البلاستيك لا يتحلل، فإنه يتراكم تدريجيا في محيطاتنا، حيث قد يستغرق تحلله قرونا دون أن يختفي تماما. ويُشكل ذلك تهديدات جسيمة للحياة المائية، وصحة الإنسان، والنظام البيئي البحري.",
    "كما تشير الدراسات إلى أنه بحلول عام 2050، قد يفوق حجم البلاستيك في المحيطات عدد الأسماك. وقد أصبحت قضية التلوث البلاستيكي واسعة الانتشار لدرجة أنها دفعت الأمم المتحدة إلى إطلاق حملة من أجل معاهدة عالمية بشأن البلاستيك.",
    "بدأت قصة البلاستيك في أوائل القرن الـ19 باختراع الإنجليزي ألكسندر باركس أول بلاستيك صناعي، وحصل على براءة اختراعه عام 1862. وقد مثّل هذا بداية حقبة جديدة في علم المواد، حيث فتحت مرونة البلاستيك ومتانته الباب أمام استخدامات لا حصر لها.",
    "شهد القرن الـ20 ثورة في إنتاج البلاستيك، تمثلت في ظهور البلاستيك الصناعي بالكامل في عام 1907، كان الكيميائي والمسوق البلجيكي ليو بايكلاند رائدا في إنتاج أول بلاستيك صناعي بالكامل (الباكليت)، مما عزز مكانة البلاستيك في قطاع التصنيع الحديث.",
    'وجاءت نقطة التحول الحقيقية بعد الحرب العالمية الثانية عندما ازدهر إنتاج البلاستيك بشكل كبير. وقد سرّعت الحرب من وتيرة التقدم في كيمياء البوليمرات، مما أدى إلى الإنتاج الضخم لمواد بلاستيكية مثل "بولي إيثيلين" و"بولي بروبيلين".',
    "وبحلول ستينيات القرن الماضي، بدأ البلاستيك يهيمن على السلع الاستهلاكية، من التغليف إلى الأدوات المنزلية. وقد عزز هذا التبني السريع من قبل الشركات والمستهلكين انخفاض تكلفة هذه المادة وتعدد استخداماتها.",
    "آنذاك، لم تتضح الآثار البيئية لطفرة البلاستيك، فعلى مدى عقود حظيت هذه المادة الثورية بالثناء لسهولتها وفائدتها، في حين تم تجاهل العواقب الطويلة المدى لإنتاجه والتخلص منه إلى حد كبير.",
    "رغم الجهود العالمية المتزايدة، لا يُعاد تدوير إلا 9% من البلاستيك. ويُعزى هذا المعدل المنخفض إلى تعقيدات إعادة تدوير المنتجات المصنوعة من أنواع مختلفة من البوليمرات، بالإضافة إلى ضعف البنية التحتية لإدارة النفايات.",
    "يُسهم البلاستيك، المنتَج من الوقود الأحفوري، بنسبة 3.4% من انبعاثات غازات الاحتباس الحراري العالمية، أي ما يُضاهي انبعاثات قطاع الطيران بأكمله. ويُنتج البشر الآن حوالي 400 مليون طن من النفايات البلاستيكية سنويا، وينتهي 60% منها في بيئتنا الطبيعية.",
    "وفقًا للتقديرات، هناك ما يقرب من 82 إلى 358 تريليون جزيء بلاستيكي عائم في محيطات العالم، مع متوسط ​​تقدير يبلغ 171 تريليون جزيء بلاستيكي مسجل في عام 2019، بمتوسط ​​وزن يبلغ 2.3 مليون طن.",
    "تتجاوز عواقب التلوث البلاستيكي البيئات البحرية؛ إذ تُهدد النظم البيئية والحياة البرية وصحة الإنسان. وقد عُثر على جزيئات بلاستيكية دقيقة ناتجة عن تحلل البلاستيك الأكبر حجما في مياه الشرب والمأكولات البحرية، وحتى في الهواء الذي نتنفسه.",
    "وبينما لا تزال هذه الجزيئات قيد البحث، تشير بعض الأبحاث إلى أنها قد تُسبب مشاكل صحية مختلفة، مثل اضطرابات الغدد الصماء، وربما السرطان، حيث وصلت جسيمات البلاستيك النانوية إلى الأعضاء الحيوية للبشر والحيوانات.",
    "ووفقًا للأمم المتحدة، فقد تناثر أكثر من 51 تريليون جزيء بلاستيكي دقيق في بحار العالم، ومن المتوقع أن تستهلك 99% من الكائنات البحرية هذه الجزيئات البلاستيكية الدقيقة بحلول عام 2050 إذا لم تُتخذ أي إجراءات لإبطاء التلوث البلاستيكي.",
    "بادرت الأمم المتحدة إلى وضع معاهدة عالمية بشأن البلاستيك. تهدف هذه المعاهدة إلى إرساء التزامات مُلزمة قانونا بين الدول للحد من إنتاج البلاستيك، وتعزيز جهود إعادة التدوير، وتشجيع البدائل المستدامة.",
    'وفي يونيو/حزيران 2023 دعا الأمين العام للأمم المتحدة أنطونيو غوتيريش "إلى الوقوف صفا واحدا الحكومات والشركات والمستهلكون لكي نتخلص من إدماننا البلاستيك وتحقيق هدف النفايات الصفرية".',
    "ففي أوائل عام 2022، اعتمدت جمعية الأمم المتحدة للبيئة القرار 5/14، الذي وافق على اعتماد معاهدة عالمية ملزمة قانونا بشأن البلاستيك بحلول نهاية عام 2024.",
    "منذ ذلك الحين، عُقدت أربع دورات للجنة التفاوض الحكومية الدولية، وانتهت أحدثها -الدورة الرابعة للجنة التفاوض الحكومية الدولية- يوم 29 أبريل/نيسان 2024. ورغم إحراز بعض التقدم في تحديد المنتجات والمواد الكيميائية الحرجة المثيرة للقلق، فإن المحادثات لم تعالج بشكل كافٍ الحاجة إلى تقليل إنتاج البلاستيك الأولي.",
    "ويتواجه معسكران على الأقل في الجولة الخامسة من المحادثات الرامية للتوصل إلى معاهدة دولية للحد من التلوث الناجم عن البلاستيك، والتي بدأت في نوفمبر/تشرين الثاني 2024، بإشراف برنامج الأمم المتحدة للبيئة.",
    'ويجمع المعسكر الأول العديد من الدول الأفريقية والأوروبية والآسيوية في "تحالف الطموح العالي"، الذي يريد معاهدة تغطي "دورة الحياة" الكاملة للمواد البلاستيكية من الإنتاج إلى النفايات.',
    "أما المعسكر الثاني فيضم دولا أخرى خصوصا المنتجة للنفط، ويرغب في أن تكون المعاهدة متعلقة فقط بإدارة النفايات. ويرى هذا المعسكر أن خفض الإنتاج ليس من أهداف المفاوضات.",
    "ويشكّل نفوذ جماعات الضغط في قطاع الصناعة عقبة كبيرة في المفاوضات. لا تزال هناك شكوك حول جدوى التوصل إلى معاهدة قابلة للتوقيع بحلول نهاية عام 2025 نظرا لتعقيدات المفاوضات، حيث ينتظر أن تنظم جولة أخرى في أغسطس/آب المقبل.",
    "من الجوانب المهمة الأخرى التي يبدو أنها غائبة في مناقشات معاهدة البلاستيك العالمية هي مساءلة الشركات الملوثة عن النفايات التي تنتجها. فقد أظهرت دراسات تلوث البلاستيك ذي العلامات التجارية أن حوالي 60 شركة مسؤولة عن أكثر من نصف تلوث البلاستيك في العالم.",
    "وللسنة السادسة على التوالي (2024) تم الاعتراف بشركة كوكاكولا كأكبر ملوث في مبادرة تدقيق العلامة التجارية العالمية، محققة رقما قياسيا جديدا بإجمالي 33 ألفا و820 قطعة من النفايات البلاستيكية.",
    "وإلى جانب إلزام الشركات بخفض إنتاج البلاستيك، يطالب أنصار البيئة أيضا بضمان مسؤولية الشركات الملوثة عن تمويل تنظيف النفايات التي تسببت فيها.",
    "وفي ظل هذه التحديات باتت الحاجة إلى معاهدة عالمية بشأن البلاستيك أكثر إلحاحا من أي وقت مضى. وسترث الأجيال القادمة مسؤولية مواجهة تفاقم التلوث البلاستيكي من أجل كوكب أكثر صحة وخاليا من أعباء التلوث البلاستيكي.",
]
arabic_health = [
    "سجلت العيادة التخصصية لجراحة المخ والأعصاب والعمود الفقري في مستشفى عدن الألماني الدولي، إنجازًا طبيًا متميزًا خلال شهر مايو الفائت 2025، حيث تم إجراء (24) عملية جراحية للعمود الفقري والانزلاقات الغضروفية، شملت حالات معقدة ونادرة، جميعها تكللت بالنجاح التام، وفقًا لما أكده الدكتور عمر التركي، استشاري جراحة المخ والأعصاب والعمود الفقري."
    "وأوضح الدكتور التركي أن العمليات تضمنت أنواعًا دقيقة ومتقدمة من التدخلات الجراحية، بعضها يُجرى لأول مرة في محافظة عدن، بل وفي اليمن عمومًا، وهو ما يعكس التقدم المستمر في مستوى الخدمات الطبية والجراحية في عدن.",
    "وذكر الدكتور عمر التركي أن من بين العمليات التي تم أجراؤها عملية نادرة جدًا ومعقدة تُجرى لأول مرة في عدن، وضمن الحالات القليلة جدًا المسجلة على مستوى اليمن،(سيتم الإعلان عن تفاصيلها في وقت لاحق).",
    "وعدد الدكتور عمر التركي أبرز العمليات التي تم إجراؤها خلال شهر مايو الفائت حيث تم اجراء (6) عمليات نوعية حديثة تشمل:",
    "(3) عمليات تثبيت للفقرات العنقية من الخلف (Lateral Mass Screw Fixation) مع تحرير تضيق القناة الشوكية.",
    "(3) عمليات زراعة غضاريف قطنية بتقنية TLIF مع إعادة الفقرات المنزاحة.",
    "كما تم إجراء (4) عمليات استئصال انزلاقات قطنية باستخدام الميكروسكوب والتدخل الجراحي المحدود (Microscopic Microdiscectomy).",
    "الإضافة إلى (4) عمليات لاستئصال غضاريف عنقية من الأمام مع زراعة غضاريف صناعية حديثة (ACDF) و(3) عمليات توسيع لتضيق القناة الشوكية القطنية (Lumbar Decompressed Laminectomy).",
    "كما تم إجراء (2) عمليات لاستئصال غضاريف قطنية مرتجعة بعد عمليات أجريت سابقًا خارج اليمن، وتعد من أصعب أنواع العمليات، و (5) عمليات لاستئصال انزلاقات غضروفية قطنية مع تثبيت الفقرات.",
    "وحالة نادرة جدًا ومعقدة ناتجة عن ترسب مادة الفلور حول الحبل الشوكي (Spinal Fluorosis)، تم التعامل معها بنجاح رغم خطورتها البالغة.",
    "أكد الدكتور عمر التركي أن ما تم تحقيقه خلال هذا شهر مايو الفائت يعكس حجم التقدم والإمكانيات المتوفرة حاليًا في عدن، سواء من حيث الكادر الطبي أو الأجهزة المتطورة، مؤكداً أن الأهم من ذلك هي ثقة المرضى الذين كان لهم الدور الأكبر في الوصول إلى هذه النتائج.",
    "وأوضح التركي أن العمليات أصبحت أكثر أمانًا ونجاحًا، لكننا نؤكد دومًا على أهمية عدم التأخير في قرار التدخل الجراحي، لأن تفاقم الانزلاقات الغضروفية مع مرور الوقت قد يؤدي إلى التصاق الأعصاب وتكلس الغضاريف، ما يصعّب العملية ويزيد من احتمالية الضرر الدائم للعصب.",
    'وأضاف التركي "نحن مستمرون في إدخال أحدث التقنيات الجراحية وتدريب الكوادر المتخصصة، ونسعى لأن تكون عدن مركزًا مرجعيًا على مستوى اليمن في هذا المجال.',
]

energy_articles = [energy_carbon_text, energy_wind_text, energy_pylons_text]
education_articles = [education_private_schools_text]
transport_articles = [
    transport_rail_renationalisation,
    transport_ulez,
    transport_tube_ebikes,
]
crime_articles = [crime_london_knives]
health_articles = [health_assisted_dying]
sadiq_khan_articles = [transport_ulez, crime_london_knives]
all_articles = (
    energy_articles
    + education_articles
    + transport_articles
    + crime_articles
    + health_articles
)

arabic_articles = [arabic_environment, arabic_education, arabic_science, arabic_health]
