name: Lint and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev

env:
  UV_VERSION: 0.7.19

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # This step is necessary if any dependencies are in private repos
      # - name: Setup git config
      #   run: |
      #     git config set --global --append url."https://fullfactdeploy:${{ secrets.GH_TOKEN_READONLY }}@github.com/".insteadOf "git@github.com:"
      #     git config set --global --append url."https://fullfactdeploy:${{ secrets.GH_TOKEN_READONLY }}@github.com/".insteadOf "ssh://git@github.com/"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Set up Python
        run: uv python install
      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "./pyproject.toml"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: "uv"
      - name: Check uv.lock is in sync with pyproject.toml
        run: uv check --lock
      - name: Install dependencies
        run: uv sync
      - name: Check typing with mypy
        run: uv run mypy --install-types --non-interactive src
      - name: Check code formatting with black
        run: uv run black --check .
      - name: Check import order
        run: uv run isort --check-only .
      - name: PEP8
        run: uv run flake8 .
      - name: Run tests
        run: uv run pytest
        env:
          PYTHONPATH: src

