name: Trigger deployment

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    name: Trigger deployment
    runs-on: ubuntu-latest
    steps:
      - uses: FullFact/ff_deploy@v1
        with:
          token: ${{ secrets.GH_TOKEN_ALPHA_INFRA_DISPATCH }}
          tag: ${{ inputs.tag }}
